
# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/URI-NamespaceMap/project>
    :perl_version_from _:main ;
    :all_from _:main ;
    :readme_from _:main ;
    :test_requires "Test::Tester" ;
    :requires "Scalar::Util", "Test::More", "Test::Builder::Module", "RDF::Trine 0.134";

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/Test/RDF.pm" .
